/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.vistaPlanilla;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author marlo
 */
public class MdiPlanillas extends javax.swing.JFrame {

    /**
     * Creates new form MdiPlanillas
     */
    public MdiPlanillas() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MdiPlanillas.MAXIMIZED_BOTH);
        this.setTitle("");
        cerrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        frmMantenimientoPerfiles2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        frmMantenimientoPerfiles1 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles5 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles6 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        frmMantenimientoPerfiles8 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles9 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        frmMantenimientoPerfiles11 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles12 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles13 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        frmMantenimientoPerfiles14 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles15 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        frmMantenimientoPerfiles4 = new javax.swing.JMenuItem();
        frmMantenimientoPerfiles17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setText("jCheckBox1");

        jMenu1.setText("Archivo");

        frmMantenimientoPerfiles2.setText("salir de menu");
        jMenu1.add(frmMantenimientoPerfiles2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Catalogos");

        frmMantenimientoPerfiles1.setText("empleados");
        jMenu2.add(frmMantenimientoPerfiles1);

        frmMantenimientoPerfiles5.setText("puestos");
        jMenu2.add(frmMantenimientoPerfiles5);

        frmMantenimientoPerfiles6.setText("deducciones");
        jMenu2.add(frmMantenimientoPerfiles6);

        frmMantenimientoPerfiles7.setText("bonificaciones");
        jMenu2.add(frmMantenimientoPerfiles7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");

        frmMantenimientoPerfiles8.setText("calcular planilla");
        jMenu3.add(frmMantenimientoPerfiles8);

        frmMantenimientoPerfiles9.setText("aplicar deduccion");
        jMenu3.add(frmMantenimientoPerfiles9);

        frmMantenimientoPerfiles10.setText("generar pagos");
        jMenu3.add(frmMantenimientoPerfiles10);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        frmMantenimientoPerfiles11.setText("empreados");
        jMenu4.add(frmMantenimientoPerfiles11);

        frmMantenimientoPerfiles12.setText("pagos");
        jMenu4.add(frmMantenimientoPerfiles12);

        frmMantenimientoPerfiles13.setText("historial");
        jMenu4.add(frmMantenimientoPerfiles13);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        frmMantenimientoPerfiles14.setText("boleta de pagos");
        jMenu5.add(frmMantenimientoPerfiles14);

        frmMantenimientoPerfiles15.setText("planilla genrar");
        jMenu5.add(frmMantenimientoPerfiles15);

        frmMantenimientoPerfiles16.setText("deduccciones");
        jMenu5.add(frmMantenimientoPerfiles16);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ayudas");

        frmMantenimientoPerfiles4.setText("manual");
        frmMantenimientoPerfiles4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                frmMantenimientoPerfiles4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        frmMantenimientoPerfiles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoPerfiles4ActionPerformed(evt);
            }
        });
        jMenu6.add(frmMantenimientoPerfiles4);

        frmMantenimientoPerfiles17.setText("acerca de");
        jMenu6.add(frmMantenimientoPerfiles17);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cerrar(){
        try 
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() 
            {
                public void windowClosing(WindowEvent e) 
                {
                    confirmarSalida();
                }
            });
            this.setVisible(true);
        } catch (Exception e) 
        {
            e.printStackTrace();
        }
    }    
    
    
 
    
    
    
    public void confirmarSalida() 
    {
        int valor=JOptionPane.showConfirmDialog(this,"¿Està seguro de cerrar?", "Advertencia", JOptionPane.YES_NO_OPTION);
                    if (valor==JOptionPane.YES_OPTION) 
                    {
                        JOptionPane.showMessageDialog(null, "Gracias por su visita, hasta pronto", "Gracias", JOptionPane.INFORMATION_MESSAGE);
                        System.exit(0);
                    }
    }
   
    
    private void mnuSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
                /*===== OPERACIÓN CERRAR SESIÓN ====
          Variable entera respuesta_cs*/

        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión",            JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        }        
    } 
    
    
    
    private void frmMantenimientoPerfiles4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_frmMantenimientoPerfiles4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_frmMantenimientoPerfiles4AncestorAdded

    private void frmMantenimientoPerfiles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoPerfiles4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmMantenimientoPerfiles4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiPlanillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiPlanillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiPlanillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiPlanillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiPlanillas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem frmMantenimientoPerfiles1;
    private javax.swing.JMenuItem frmMantenimientoPerfiles10;
    private javax.swing.JMenuItem frmMantenimientoPerfiles11;
    private javax.swing.JMenuItem frmMantenimientoPerfiles12;
    private javax.swing.JMenuItem frmMantenimientoPerfiles13;
    private javax.swing.JMenuItem frmMantenimientoPerfiles14;
    private javax.swing.JMenuItem frmMantenimientoPerfiles15;
    private javax.swing.JMenuItem frmMantenimientoPerfiles16;
    private javax.swing.JMenuItem frmMantenimientoPerfiles17;
    private javax.swing.JMenuItem frmMantenimientoPerfiles2;
    private javax.swing.JMenuItem frmMantenimientoPerfiles4;
    private javax.swing.JMenuItem frmMantenimientoPerfiles5;
    private javax.swing.JMenuItem frmMantenimientoPerfiles6;
    private javax.swing.JMenuItem frmMantenimientoPerfiles7;
    private javax.swing.JMenuItem frmMantenimientoPerfiles8;
    private javax.swing.JMenuItem frmMantenimientoPerfiles9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
