/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


// 1. Para el manejo de Listas (necesario para traer usuarios y perfiles)
import java.util.List;
import java.util.ArrayList;

// 2. Para las Tablas y Mensajes de alerta
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

import Controlador.clsAsignacionPerfilUsuario; 
import Modelo.AsignacionPerfilUsuarioDAO;    
import Controlador.clsUsuario;               
import Modelo.UsuarioDAO;                  
import Modelo.BitacoraDAO;                   
import Controlador.clsUsuarioConectado;       


import Controlador.clsPerfil; 
import Modelo.PerfilDAO;

/**
 *
 * @author JENNIFER BARRIOS 9959-24-10016
 */



public class frmProcesoPerfilUsuario extends javax.swing.JInternalFrame {


private static final int Aplcodigo = 10010; 
    int idUsuarioConectado = Controlador.clsUsuarioConectado.getUsuId();


    Modelo.AsignacionPerfilUsuarioDAO asignacionDAO = new Modelo.AsignacionPerfilUsuarioDAO();
    Controlador.clsAsignacionPerfilUsuario asignacionControlador = new Controlador.clsAsignacionPerfilUsuario();
    Modelo.BitacoraDAO bitacoraDAO = new Modelo.BitacoraDAO();
    
    
    public void llenarComboUsuario() {
    Modelo.UsuarioDAO usuarioDAO = new Modelo.UsuarioDAO();

    List<Controlador.clsUsuario> usuarios = usuarioDAO.consultaUsuarios(); 
    
    cboUsuario.removeAllItems();
    cboUsuarioId.removeAllItems();
    
    for (Controlador.clsUsuario usuario : usuarios) {
        cboUsuario.addItem(usuario.getUsuNombre()); 
        cboUsuarioId.addItem(String.valueOf(usuario.getUsuId())); 
    }
}
    
    public void llenarTablas(int idUsuario) {
        
        DefaultTableModel modeloDisp = (DefaultTableModel) tablaDisponibles.getModel();
    DefaultTableModel modeloAsig = (DefaultTableModel) tablaAsignados.getModel();
    modeloDisp.setRowCount(0); 
    modeloAsig.setRowCount(0); 

    try {
        // 1. Obtenemos todos los perfiles existentes
        // Creamos una bitácora vacía solo para cumplir con el requisito del PerfilDAO
        Controlador.clsBitacora bitTemp = new Controlador.clsBitacora();
        PerfilDAO daoPerfil = new PerfilDAO();
        List<Controlador.clsPerfil> todosLosPerfiles = daoPerfil.obtenerPerfiles(bitTemp);

        // 2. Usamos tu AsignacionPerfilUsuarioDAO para ver cuáles ya tiene el usuario
        AsignacionPerfilUsuarioDAO daoAsignacion = new AsignacionPerfilUsuarioDAO();

        for (Controlador.clsPerfil perfil : todosLosPerfiles) {
            // Usamos tu método .buscar(usuario, perfil) para saber si ya existe la relación
            boolean existe = daoAsignacion.buscar(idUsuario, perfil.getPercodigo());

            if (existe) {
                // Si ya existe, va a la tabla de ASIGNADOS (derecha)
                modeloAsig.addRow(new Object[]{perfil.getPercodigo(), perfil.getPernombre()});
            } else {
                // Si no existe, va a la tabla de DISPONIBLES (izquierda)
                modeloDisp.addRow(new Object[]{perfil.getPercodigo(), perfil.getPernombre(), perfil.getPerestado()});
            }
        }
    } catch (Exception e) {
        System.err.println("Error en llenarTablas: " + e);
    }
    
        //Este metódo lo podré terminar hasta la modificacion de los errores de PerfilDAO
}
    
    /**
     * Creates new form MantenimientoAsignacionPerfilUsuario
     */
   public frmProcesoPerfilUsuario() {
       
    initComponents(); 
    
    this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    this.setClosable(true);
    this.setIconifiable(true);
    this.setMaximizable(true);
    this.setResizable(true);
    this.setSize(800, 600); 
    
    llenarComboUsuario();
    Modelo.UsuarioDAO usuarioDAO = new Modelo.UsuarioDAO();
    List<Controlador.clsUsuario> usuarios = usuarioDAO.consultaUsuarios(); 
    
    // 1. Limpiamos los combos
    cboUsuario.removeAllItems();
    cboUsuarioId.removeAllItems();
    
    // 2. Llenamos ambos combos
    for (Controlador.clsUsuario usuario : usuarios) {
        cboUsuario.addItem(usuario.getUsuNombre()); 
        cboUsuarioId.addItem(String.valueOf(usuario.getUsuId())); 
    }
    
    // 3. Forzamos una selección inicial solo si hay datos
    if (cboUsuario.getItemCount() > 0) {
        cboUsuario.setSelectedIndex(0);
        cboUsuarioId.setSelectedIndex(0);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboUsuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboUsuarioId = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDisponibles = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAsignados = new javax.swing.JTable();
        btnAsignarUno = new javax.swing.JButton();
        btnQuitarUno = new javax.swing.JButton();
        btnAsignarTodos = new javax.swing.JButton();
        btnQuitarTodos = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MANTENIMIENTO ASIGNACIÓN PERFIL USUARIO.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 23, -1, -1));

        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 62, -1, -1));

        cboUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cboUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 57, 154, -1));

        jLabel3.setText("Codigo Usuario: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 62, -1, -1));

        cboUsuarioId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboUsuarioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuarioIdActionPerformed(evt);
            }
        });
        getContentPane().add(cboUsuarioId, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 57, 153, -1));

        jLabel4.setText("PERFILES DISPONIBLES:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 123, -1, -1));

        tablaDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Percodigo", "PerNombre", "PerEstado"
            }
        ));
        jScrollPane1.setViewportView(tablaDisponibles);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 360, -1));

        jLabel5.setText("PERFILES ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 123, -1, -1));

        tablaAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Percodigo", "PerNombre"
            }
        ));
        jScrollPane2.setViewportView(tablaAsignados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 151, 343, -1));

        btnAsignarUno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAsignarUno.setText(">");
        btnAsignarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignarUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 232, -1, -1));

        btnQuitarUno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuitarUno.setText("<");
        btnQuitarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarUnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuitarUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 350, -1, -1));

        btnAsignarTodos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAsignarTodos.setText(">>");
        btnAsignarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 286, -1, -1));

        btnQuitarTodos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuitarTodos.setText("<<");
        btnQuitarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuitarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 412, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarUnoActionPerformed
                                           
    int filaSeleccionada = tablaAsignados.getSelectedRow();

    if (filaSeleccionada != -1) {
        int idPerfil = Integer.parseInt(tablaAsignados.getValueAt(filaSeleccionada, 0).toString());
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());

        int resultado = asignacionDAO.eliminar(idUsuarioDestino, idPerfil);

        if (resultado > 0) {
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "QUITAR UN PERFIL INDIVIDUAL AL USUARIO");
            
            DefaultTableModel modeloDisponibles = (DefaultTableModel) tablaDisponibles.getModel();
            DefaultTableModel modeloAsignados = (DefaultTableModel) tablaAsignados.getModel();

           
            Object[] fila = {
                tablaAsignados.getValueAt(filaSeleccionada, 0), // ID
                tablaAsignados.getValueAt(filaSeleccionada, 1), // Nombre
                "Disponible" // 
            };

            modeloDisponibles.addRow(fila);
            modeloAsignados.removeRow(filaSeleccionada);
            
            JOptionPane.showMessageDialog(null, "Perfil quitado con éxito.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecciona un perfil de la tabla de asignados.");
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarUnoActionPerformed

    private void btnQuitarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarTodosActionPerformed
                                             
    if (cboUsuarioId.getSelectedItem() != null) {
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
        DefaultTableModel modeloAsignados = (DefaultTableModel) tablaAsignados.getModel();
    
        for (int i = modeloAsignados.getRowCount() - 1; i >= 0; i--) {
            int idPerfil = Integer.parseInt(modeloAsignados.getValueAt(i, 0).toString());
            asignacionDAO.eliminar(idUsuarioDestino, idPerfil);
        }
        
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "QUITAR TODOS LOS PERFILES");
        llenarTablas(idUsuarioDestino); // Esto refresca ambas tablas de la Base de Datos
        JOptionPane.showMessageDialog(null, "Se han quitado todas las asignaciones.");
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarTodosActionPerformed

    private void btnAsignarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTodosActionPerformed

    if (cboUsuarioId.getSelectedItem() != null) {
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
        DefaultTableModel modeloDisponibles = (DefaultTableModel) tablaDisponibles.getModel();
        
        // Se recorre de abajo hacia arriba para evitar errores de índice
        for (int i = modeloDisponibles.getRowCount() - 1; i >= 0; i--) {
            int idPerfil = Integer.parseInt(modeloDisponibles.getValueAt(i, 0).toString());
            asignacionDAO.insertar(idUsuarioDestino, idPerfil);
        }
        
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "ASIGNAR TODOS LOS PERFILES");
        llenarTablas(idUsuarioDestino);
        JOptionPane.showMessageDialog(null, "Todos los perfiles han sido asignados.");
    }


        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarTodosActionPerformed

    private void btnAsignarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUnoActionPerformed

    int filaSeleccionada = tablaDisponibles.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        // 1. Extraer el ID del perfil (está en la columna 0)
        int idPerfil = Integer.parseInt(tablaDisponibles.getValueAt(filaSeleccionada, 0).toString());
        // 2. Extraer el ID del usuario del ComboBox
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
        
        // 3. Ejecutar la inserción usando el DAO
        int resultado = asignacionDAO.insertar(idUsuarioDestino, idPerfil);

        if (resultado > 0) {
           bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "ASIGNÓ PERFIL: " + idPerfil);
           llenarTablas(idUsuarioDestino); // Refresca las tablas
           JOptionPane.showMessageDialog(null, "Asignación exitosa");
            }
    } else {
        JOptionPane.showMessageDialog(null, "Selecciona un perfil de la tabla de disponibles.");
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarUnoActionPerformed

    private void cboUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuarioActionPerformed
                                      
if (cboUsuario.getItemCount() > 0 && cboUsuario.getSelectedIndex() != -1) {
        if (cboUsuarioId.getItemCount() > cboUsuario.getSelectedIndex()) {
            cboUsuarioId.setSelectedIndex(cboUsuario.getSelectedIndex());
            
            int idSeleccionado = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
            llenarTablas(idSeleccionado);
        }
    }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUsuarioActionPerformed

    private void cboUsuarioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuarioIdActionPerformed
        if (cboUsuarioId.getItemCount() > 0 && cboUsuarioId.getSelectedIndex() != -1) {
        if (cboUsuario.getItemCount() > cboUsuarioId.getSelectedIndex()) {
            cboUsuario.setSelectedIndex(cboUsuarioId.getSelectedIndex());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUsuarioIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProcesoPerfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarTodos;
    private javax.swing.JButton btnAsignarUno;
    private javax.swing.JButton btnQuitarTodos;
    private javax.swing.JButton btnQuitarUno;
    private javax.swing.JComboBox<String> cboUsuario;
    private javax.swing.JComboBox<String> cboUsuarioId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAsignados;
    private javax.swing.JTable tablaDisponibles;
    // End of variables declaration//GEN-END:variables
}
